create table books(
Book_Id int primary key,
Title VARCHAR(225) NOT NULL,
Author VARCHAR(225) NOT NULL,
Publisher VARCHAR(225),
Publication_Year INT,
Total_Copies INT NOT NULL,
Copies_Available INT NOT NULL
);

Select * from books;

create table users(
User_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
First_Name VARCHAR(100) NOT NULL,
Last_Name VARCHAR(100) NOT NULL,
Email VARCHAR(150) UNIQUE NOT NULL,
Phone_Number VARCHAR(15),
Membership_Date Date DEFAULT SYSDATE NOT NULL
);
Select * from users;

create table reservations(
Reservation_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
User_id INT NOT NULL,
Book_Id INT NOT NULL,
Reserved_At timestamp default current_timestamp,
Expires_at TIMESTAMP not null,
Status VARCHAR(20) DEFAULT 'active' NOT NULL,
CONSTRAINT fk_res_user FOREIGN KEY (User_id) REFERENCES Users(User_id),
CONSTRAINT fk_res_book FOREIGN KEY (Book_Id) REFERENCES Books(Book_Id)
);

Select * from reservations;

create table borrow_history(
Borrow_id NUMBER GENERATED BY DEFAULT ON NULL AS IDENTITY primary key,
User_id INT NOT NULL,
Book_Id INT Not null,
Borrowed_at TIMESTAMP Default current_timestamp,
Due_Date Date not null,
returned_at Timestamp,
CONSTRAINT fk_borrow_user FOREIGN KEY (User_id) REFERENCES Users(User_id),
CONSTRAINT fk_borrow_book FOREIGN KEY (Book_Id) REFERENCES Books(Book_Id)
);

select * from borrow_history;
